### ISSUE TITLE
java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater

### ISSUE THREAD

**Issue by nigelunderwood** [appcelerator-archive/ti.inappbilling#29] opened 2018-03-17 08:28 UTC
Doesn't seem to work with SDK 7.1.0 as its it's attempting to use a class thats only available in version 27.1.0 of the support libraries

**Comment by hansemannn** [comment] 2018-03-17 09:40
Duplicate of the JIRA ticket, please do not open multiple tickets.

**Closed as completed by hansemannn** 2018-03-17 09:40 UTC
